spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT-SECRET}
            scope: name,email,avatar_url
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT-SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - profile
              - email


# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: ${JWT_SECRET}

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    token-secret: ${TOKEN_SECRET}
    token-expiry: ${TOKEN_EXPIRY} # 24시간
    refresh-token-expiry: ${REFRESH_TOKEN_EXPIRY} # 7일